### ISSUE TITLE
    Finished dev [unoptimized + debuginfo] target(s) in 4.41s      Running `target/debug/mino` Error: S3Error { description: Some("Io Error: failed to lookup address information: nodename nor servname provided, or not known"), data: None, source: None }

### ISSUE THREAD

**Issue by tx991020** [durch/rust-s3#108] opened 2020-08-16 15:10 UTC
use s3::bucket::Bucket;

use s3::creds::Credentials;
use s3::region::Region;
use s3::S3Error;
use std::fs::File;

struct Storage {
    name: String,
    region: Region,
    credentials: Credentials,
    bucket: String,
    location_supported: bool,
}

fn main() -> Result<(), S3Error> {
    // region_name = "nl-ams".to_string();
    // endpoint = "https://s3.nl-ams.scw.cloud".to_string();
    // region = Region::Custom { region: region_name, endpoint };
    let aws = Storage {
        name: "aws".into(),
        region: Region::Custom {
            region: "us-east-1".to_string(),
            endpoint: "http://114.55.145.17:5432".to_string(),
        },
        credentials: Credentials::new(Some("admin"), Some("admin123"), None, None, None).unwrap(),
        // credentials: Credentials::from_env_specific(Some("admin"), Some("admin123"), None, None)?,
        bucket: "test".to_string(),
        location_supported: true,
    };

    let bucket = Bucket::new(&aws.bucket, aws.region, aws.credentials)?;

    let (_, code) =
        bucket.put_object_blocking("test_file", "I want to go to S3".as_bytes(), "text/plain")?;
    // println!("{}", bucket.presign_get("test_file", 604801)?);
    assert_eq!(200, code);
    Ok(())
}

**Comment by durch** [comment] 2020-08-17 09:10
@tx991020 looks like a connectivity issues, are you absolutely positive something is listening on `http://114.55.145.17:5432` ?

**Comment by tx991020** [comment] 2020-08-17 09:19
yes .  use  golang  SDK  It is ok.


package main

import (
	"context"
	"log"


	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	endpoint := "114.55.145.17:5432"
	accessKeyID := "admin"
	secretAccessKey := "admin123"
	useSSL := false

	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		log.Fatalln(err)
	}

	// Make a new bucket called mymusic.
	bucketName := "test"
	location := "us-east-1"

	err = minioClient.MakeBucket(context.Background(), bucketName, minio.MakeBucketOptions{Region: location})
	if err != nil {
		// Check to see if we already own this bucket (which happens if you run this twice)
		exists, errBucketExists := minioClient.BucketExists(context.Background(),bucketName)
		if errBucketExists == nil && exists {
			log.Printf("We already own %s\n", bucketName)
		} else {
			log.Fatalln(err)
		}
	} else {
		log.Printf("Successfully created %s\n", bucketName)
	}

	// Upload the zip file
	objectName := "foo.txt"
	filePath := "/Users/andy/CLionProjects/todo/mino/src/foo.txt"
	contentType := "application/txt"

	// Upload the zip file with FPutObject
	n, err := minioClient.FPutObject(context.Background(), bucketName, objectName, filePath, minio.PutObjectOptions{ContentType: contentType})
	if err != nil {
		log.Fatalln(err)
	}

	log.Printf("Successfully uploaded %s of size %d\n", objectName, n.Size)
}

**Comment by tx991020** [comment] 2020-08-17 09:20
looks like reqwest  dns error

**Comment by tx991020** [comment] 2020-08-17 09:22
Error: S3Error { description: Some("error sending request for url (http://test1.114.55.145.17:5432/?delimiter=%2F&prefix=%2F&list-type=2): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known"), data: None, source: Some(Req(reqwest::Error { kind: Request, url: "http://test1.114.55.145.17:5432/?delimiter=%2F&prefix=%2F&list-type=2", source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" })) })) }

**Comment by durch** [comment] 2020-08-18 13:06
Might be the port tripping it up, I'll do some debugging

**Comment by durch** [comment] 2020-08-24 18:46
@tx991020 sorry this took so long. The issue is with the subdomain style. If you create the bucket with `Bucket::new_with_path_style` instead of `Bucket::new` it should work as expected, method signatures are the same.

**Comment by tx991020** [comment] 2020-08-25 04:07
thank you very much  @durch

**Comment by durch** [comment] 2020-08-25 06:52
Closing for now, please reopen if the issue resurfaces in a different context :)

**Closed by durch** 2020-08-25 06:52 UTC
Labels: bug
