### ISSUE TITLE
socks5 integration

### ISSUE THREAD

**Issue by Masber** [durch/rust-s3#367] opened 2023-11-02 13:23 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to customize the http client with socks5 configuration.

**Describe the solution you'd like**
I would like to be able to do something like:
```
    let socks_http_connector = SocksConnector {
        proxy_addr: std::env::var("SOCKS5").unwrap().parse::<Uri>().unwrap(), // scheme is required by HttpConnector
        auth: None,
        connector: http_connector.clone(),
    };
```
And then inject this http_connector to the http client used by this library (I assume is reqwest)

**Describe alternatives you've considered**
An alternative (and better solution) would be to add a function to enable socks5 by specifying the socks5 proxy url, credentials, etc.

**Additional context**
For now, I would be happy if someone just tells me how I could inject my hyper client (with socks5 and rustls) into this library

**Comment by Masber** [comment] 2023-11-06 16:01
Hi, any help on this?

**Comment by durch** [comment] 2024-06-17 06:51
Duplicate of #387

**Comment by durch** [comment] 2024-09-01 09:06
[Added support for `reqwest::Proxy`, with `tokio` backend only](https://docs.rs/rust-s3/0.36.0-alpha.3/s3/bucket/struct.Bucket.html#method.set_proxy)

**Closed by durch** 2024-09-01 09:06 UTC
Labels: duplicate, enhancement
