### ISSUE TITLE
put_multipart_chunk should NOT consume the chunk parameter

### ISSUE THREAD

**Issue by szguoxz** [durch/rust-s3#375] opened 2024-01-04 15:03 UTC
pub async fn put_multipart_chunk(
    &self,
    chunk: vec<u8>,
    path: &str,
    part_number: u32,
    upload_id: &str,
    content_type: &str,
) -> Result<Part, S3Error>
==================
parameter chunk really should be of type &[u8] instead of a vec.
This makes a big difference as if my part is 100MB, you will require 100MB more memory. use &[u8] will allow me to reuse the read buffer.

**Comment by urkle** [comment] 2024-01-04 15:55
Duplicate of #351

**Closed** 2024-06-17 07:05 UTC
