### ISSUE TITLE
HTTP connection to blobstore is never closed when uploading object

### ISSUE THREAD

**Issue by jspawar** [durch/rust-s3#104] opened 2020-07-23 06:36 UTC
**Describe the bug**
Call to `put_object` (with `await`) in an `async` function consistently never finishes. Upon inspection via `lsof -i` I see that my process has indeed opened a connection to the blobstore (in this case the S3-compatible endpoint for a GCS bucket):

```sh
my_binary 87130 me   23u  IPv4 0xc9ce8b2d93753fb7      0t0  TCP X.X.X.X:62088->172.217.164.112:https (ESTABLISHED)
```

But it then consistently remains stuck having not actually closed the underlying client's end of the TCP socket for the HTTP connection as I see it stuck in the `CLOSE_WAIT` state (at least for a few minutes after which point I kill my binary's process):

```sh
my_binary 87130 me   23u  IPv4 0xc9ce8b2d93753fb7      0t0  TCP X.X.X.X:62088->172.217.164.112:https (CLOSE_WAIT)
```

**To Reproduce**
Snippet of code:

```rust
        let app_bits_bucket = s3::bucket::Bucket::new(
            "my-bucket",
            s3::region::Region::Custom {
                region: "us-west2".to_owned(),
                endpoint: "https://storage.googleapis.com".to_owned(),
            },
            s3::creds::Credentials::new(
                Some("access-key"),
                Some("secret-key"),
                None,
                None,
                None,
            )
            .await
            .unwrap(),
        )
        .unwrap();
        debug!("uploading to blobstore...");
        app_bits_bucket
            .put_object(
                format!("some-object/{}", guid),
                &raw_data[..],
                "application/octet-stream",
            )
            .await
            .unwrap();
        debug!("finished uploading to blobstore!");
```

**Expected behavior**
The TCP connection to close subsequently causing the HTTP connection to close and then at least receive some sort of response from the call to `put_object` be it erroneous or not. 

**Environment**
 - Rust version: 1.43.1
 - lib version: 0.22.12 (default features)

**Additional context**
Would love any advice on how to debug this further. Perhaps the response that has been streamed back via `tcpdump` or `wireshark`? Admittedly my knowledge of both is very limited though, especially when it comes to intercepting SSL/TLS-encrypted requests

**Comment by durch** [comment] 2020-07-23 15:49
@jspawar thank you for the report, I've not tested this agains GCP ever, so it might be something specific to their implementation. I'll take a look and report back.

**Comment by jspawar** [comment] 2020-07-23 23:31
@durch Great, thank you! Let me know if you'd like anything more from me of course, happy to help

**Comment by jspawar** [comment] 2020-07-24 00:22
Interestingly, I decided to try to use a Minio I deployed myself to a Kubernetes cluster I had lying around and ran into the exact same problem...

FWIW: I've used that particular Minio deployment for other projects and it has been working fine without issue (just to rule out any possible weirdness with the blobstore itself)

**Comment by durch** [comment] 2020-07-24 11:08
Oh very interesting, thank you for more info, points to a more general problem with custom regions possibly, will be easier to investigate for sure.

**Comment by durch** [comment] 2020-10-03 19:44
@jspawar I wonder if you can still reproduce the issue with ^0.25. I've just tested it and it seems to be closing ok, I've added a test to the lib to test GCP specifically so hopefully it catches it even if it is something intermittent...

**Comment by durch** [comment] 2020-10-19 18:09
Closing for now, feel free to reopen if the issue persists

**Closed by durch** 2020-10-19 18:09 UTC
Labels: bug
