### ISSUE TITLE
Does not work with Minio

### ISSUE THREAD

**Issue by fredyflores96** [durch/rust-s3#162] opened 2021-01-13 21:21 UTC
**Describe the bug**
I am not sure if this crate supports connecting to minio but I assume it may have been intended to since minio is on the the keywords listed when I look up the library. I am having lots of trouble making any requests to minio to create buckets or access any files. 

**To Reproduce**
Try to connect to any local minio pod and you will end up with XMinioUnknownAPIRequest responses. 

**Expected behavior**
I would expect it to support minio since minio can use the aws s3 cli to make its resquests. 

**Environment**
 - 1.44.0
 - 0.26.4

**Additional context**
Please let me know if I am just incorrectly trying to make calls to minio or if I am even supposed to try to use this library to try to communicate to minion.

some sample code I tried to use to connect 

```
struct Storage {
    name: String,
    region: Region,
    credentials: Credentials,
    bucket: String,
    location_supported: bool,
}

#[tokio::main]
async fn main()-> Result<(), S3Error> {
    let minio = Storage {
        name: "minio".into(),
        region: Region::Custom {
            region: "us-east-1".into(),
            endpoint: "http://localhost:9000".into(),
        },
        credentials: Credentials::from_profile(Some("minio-local"))?,
        bucket: "rust-s3".to_string(),
        location_supported: false,
    };

    for backend in vec![minio] {
        println!("Running {}", backend.name);
        let config = BucketConfiguration::default();
        let create_bucket_response = Bucket::create(&backend.bucket, backend.region, backend.credentials, config).await?;

        println!("{:#?}",create_bucket_response.response_text);
    }
    Ok(())
}
```

---this is the response when I print the response text:

`<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at /</Message><Resource>/</Resource><RequestId></RequestId><HostId>780ff3b5-f965-4153-ad4d-893237116cb2</HostId></Error>`

Thanks!

**Comment by durch** [comment] 2021-01-14 10:50
Hi @fredyflores96 it should work with `minio` the gotcha is to use `path_style` buckets - [Bucket::new_with_path_style](https://docs.rs/rust-s3/0.26.4/s3/bucket/struct.Bucket.html#method.new_with_path_style)

**Comment by fredyflores96** [comment] 2021-01-14 15:31
is there a way to send a create bucket request? I know Bucket::create() is meant to do that and I also see that the 0.27.0 - beta(X) have create_with_path_style(). since Bucket::create() doesn't work with minio at this moment. Is there a different way to create a bucket in minio 0.26.4?

**Comment by durch** [comment] 2021-01-15 10:11
Yes! It is a bit clunky tough, you need to create bucket first using `Bucket::create()` then use [`Bucket::set_path_style()`](https://docs.rs/rust-s3/0.26.4/s3/bucket/struct.Bucket.html#method.set_path_style) to configure it.

**Comment by gwierzchowski** [comment] 2021-01-21 11:44
Approach with `new_with_path_style` does not work either with 0.26.4, or 0.27-beta8/async.
All next calls like: `list_blocking` or `put_object_blocking` end with code 400, and meesage: `400 Bad Request: malformed Host header`.
I'm connecting to minio run locally from docker on Windows 10, and using:
```rust
    let region = s3::Region::Custom {
        region: "eu-central-1".into(),
        endpoint: "http://localhost:9000/".into(),
    };
    let credentials = Credentials::new(
        Some("minioadm"),
        Some("minioadm-key"),
        None,
        None,
        None
    )?;
```

**Comment by milenkovicm** [comment] 2021-01-22 09:29
helper function, something like:

```rust
async fn create_with_path_style(
    name: &str,
    region: Region,
    credentials: Credentials,
    mut config: BucketConfiguration,
) -> Result<CreateBucketResponse, dyn Error> {
    config.set_region(region.clone());
    let command = Command::CreateBucket { config };
    let bucket = Bucket::new_with_path_style(name, region, credentials)?;
    let request = Request::new(&bucket, "", command);
    let (data, response_code) = request.response_data_future(false).await?;

    let response_text =
        std::str::from_utf8(&data)?;

    Ok(CreateBucketResponse {
        bucket,
        response_text: response_text.to_string(),
        response_code,
    })
}
```

may help.

it is a copy of `create` with difference of `Bucket::new_with_path_style(name, region, credentials)?;`

`0.27` branch has `create_with_path_style` maybe 0.26 could get it as well, as it wont break interface. 

wdyt @durch ?

**Comment by durch** [comment] 2021-01-29 21:17
@milenkovicm I like it in principle, I've been a bit strapped for time, apologies for that, will try and make the update next week

**Comment by durch** [comment] 2021-02-06 09:37
@milenkovicm, I've added a [minio test](https://github.com/durch/rust-s3/blob/3662f0c2ac2c7d9fe88287023e6e40ddd49a9550/s3/src/bucket.rs#L1974), and it passes in 0.27.0-beta10, I wonder if you could try that version and report back. Thank you

**Comment by milenkovicm** [comment] 2021-02-06 09:55
Hi @durch I don't quite understand your comment. @gwierzchowski complained that create_with_path_style does not work (not available) in 0.26 and I suggested if you could backport it from 0.27 to 0.26. That would help with minio integration

**Comment by durch** [comment] 2021-02-08 10:50
Reading that back, its quite unclear :), sorry about that. 

What I'm saying is that I can't reproduce the `minio` failures in `0.27.*`. I'd rather avoid adding patches to 0.26 so I've added a test for the common operations and it seems to be passing, I need some help to get it to fail :)

I'm running `minio` in a docker:

```bash
docker run -p 9000:9000 \
  -e "MINIO_ROOT_USER=test" \
  -e "MINIO_ROOT_PASSWORD=test1234" \
  minio/minio server /data
```

After creating the `rust-s3` bucket I can run `PUT`, `GET` and `DELETE` operations against it. This leads me to think that the issue is somewhere else, I'm wondering if @gwierzchowski can help me get the test to fail, in order to know what to go and fix :)

**Comment by milenkovicm** [comment] 2021-02-08 10:56
I think it works well with `0.27` the problem is with `0.26` as he pointed out in his comment.

**Comment by durch** [comment] 2021-02-10 11:59
I that case I'd nudge everyone towards an upgrade to 0.27, it'll be out of beta soon-ish :). Closing for now @fredyflores96 please reopen if you feel we can do something else here

**Closed by durch** 2021-02-10 11:59 UTC
Labels: bug

**Comment by gwierzchowski** [comment] 2021-02-16 19:57
@durch, @milenkovicm . I'm sorry but maybe I introduced some confusion.
I finally tracked down that my error (code 400) was because spare slash in endpoint string: `http://localhost:9000/`.
That said I think error handling could be improved, as by symptoms it was not obvoius where the problem was.
Here I my suggestion what could be done:
- `new_with_path_style` could work in way more similar to `create_with_path_style` - i.e. it could try to connect to store and check if required bucket exist, and return error (with readable error string) if not exist, or endpoint is not correct.
Currently this function silently returns Ok, and only next call that actually connect to store (e.g. `put_object`) retuns code - 400 without any text or indication where the problem is - this is little confusing.

After corecting endpoint I confirm that all works correctly.

BTW: Other small issue (non related) which I noticed in Cargo.toml, I think too small to raise special item):
`tokio-stream = "0.1"` - this means that tokio is effectively non-optional (it should be included in `with-tokio` feature)
